esphome:
  name: test-empty-binaryx

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
 - source:
     type: git
     url: https://github.com/gabrielcor/esphome-externalcomponents
   refresh: 1s
   components: [empty_binaryx]
     
sensor:
  - platform: empty_binaryx
    id: sensorbin

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
     static_ip: 192.168.1.78
     gateway: 192.168.1.1
     subnet: 255.255.255.0  

captive_portal:
