esphome:
  name: test-ticket-dispenser
  friendly_name: test_ticket_dispenser

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
     static_ip: 192.168.1.80
     gateway: 192.168.1.1
     subnet: 255.255.255.0  

captive_portal:

external_components:
 - source:
     type: git
     url: https://github.com/gabrielcor/esphome-externalcomponents
   components: [ticket_dispenser]
   refresh: 1s
     
sensor:
  - platform: ticket_dispenser
    pin: 19
    name: "Ticket Dispenser"
    id: sensor_ticket_dispenser
    total:
      name: "Total Pulses"

button:
  - platform: template
    name: "Set Zero"
    on_press:
      - ticket_dispenser.set_total_pulses:
          id: sensor_ticket_dispenser
          value: !lambda 'return 0;'

