esphome:
  name: test-external_components

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
 - source:
     type: git
     url: https://github.com/gabrielcor/esphome-externalcomponents
   components: [empty_binary_sensor]
     
empty_binary_sensor:
   id: sensorbin
