esphome:
  name: test-external-component01
  friendly_name: test-external-component01

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
 - source:
     type: git
     url: https://github.com/gabrielcor/esphome-externalcomponents
   refresh: 1s
   components: [empty_binaryx]
     
sensor:
  - platform: empty_binaryx
    id: sensorbin
    name: "Sensor BinaryX"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
     static_ip: 192.168.1.79
     gateway: 192.168.1.1
     subnet: 255.255.255.0  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-External-Component01"
    password: "wJQzcMVgaUZW"

captive_portal:
