esphome:
  name: test-empty-binaryx
  friendly_name: test_knock_pattern_detector

esp32:
  board: esp32-s3-devkitc-1
  #board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:

ota:
 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
     static_ip: 192.168.1.79
     gateway: 192.168.1.1
     subnet: 255.255.255.0  

captive_portal:

external_components:
 - source:
     type: git
     url: https://github.com/gabrielcor/esphome-externalcomponents
   refresh: 1s
   components: [knock_pattern_detector]
     
sensor:
  - platform: adc
    pin: 4
    id: adcsensor2knock
    name: "Sensor ADC 4 Knock"
    update_interval: 600s

  - platform: knock_pattern_detector
    id: sensor_knock
    maglock_pin: 34
    adc: adcsensor2knock
    knock_pattern: [512,256,256,512,1024,512]
    knock_sensor_threshold: 1

button:
  - platform: restart
    name: "Restart"