esphome:
  name: test-external_components

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
 - source:
     type: local
     path: local_components
   components: [empty_binaryx]
     
sensor:
  - platform: empty_binaryx
    id: sensorbin
