
esphome:
  name: test_knock_pattern_detector
  friendly_name: test_knock_pattern_detector

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
 - source:
     type: local
     path: components
   components: [knock_pattern_detector]
     
sensor:
  - platform: knock_pattern_detector
    id: sensor_knock
    pin: 33
    knock_pattern: [512,256,256,512,1024,512]
    knock_sensor_threshold: 1
