
esphome:
  name: test_knock_pattern_detector
  friendly_name: test_knock_pattern_detector

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
 - source:
     type: local
     path: components
   components: [knock_pattern_detector]

sensor:
  - platform: adc
    pin: 33
    id: adcsensor2knock
    name: "Sensor ADC 4 Knock"
  - platform: knock_pattern_detector
    id: sensor_knock
    maglock_pin: 34
    adc: adcsensor2knock
    knock_pattern: [512,256,256,512,1024,512]
    knock_sensor_threshold: 1
